services:
  db:
    image: pgvector/pgvector:pg18
    ports:
      - 5432:5432
    volumes:
      - pg_data_dev:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  pg_data_dev:
