defmodule NoteManager.Repo.Migrations.DownsizeDevModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notes) do
      modify :embedding, :vector, size: 384
    end
  end

  def down do
    alter table(:notes) do
      modify :embedding, :vector, size: 1024
    end
  end
end
