defmodule NoteManager.Repo.Migrations.AddVectorIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX vector_idx ON notes USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)
    """)
  end

  def down do
    execute("""
    DROP INDEX vector_idx;
    """)
  end
end
