defmodule NoteManager.Repo.Migrations.AddedNoteLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:note_links, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_note_id,
          references(:notes,
            column: :id,
            name: "note_links_source_note_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :target_note_id,
          references(:notes,
            column: :id,
            name: "note_links_target_note_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end
  end

  def down do
    drop constraint(:note_links, "note_links_source_note_id_fkey")

    drop constraint(:note_links, "note_links_target_note_id_fkey")

    drop table(:note_links)
  end
end
