defmodule NoteManager.Repo.Migrations.AddCascadingDestroyToNoteLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:note_links, "note_links_target_note_id_fkey")

    drop constraint(:note_links, "note_links_source_note_id_fkey")

    alter table(:note_links) do
      modify :source_note_id,
             references(:notes,
               column: :id,
               name: "note_links_source_note_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :target_note_id,
             references(:notes,
               column: :id,
               name: "note_links_target_note_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:note_links, "note_links_source_note_id_fkey")

    drop constraint(:note_links, "note_links_target_note_id_fkey")

    alter table(:note_links) do
      modify :target_note_id,
             references(:notes,
               column: :id,
               name: "note_links_target_note_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :source_note_id,
             references(:notes,
               column: :id,
               name: "note_links_source_note_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
